import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { toPascalCase } from './utils/naming';
import { getAllIconNames } from './utils/file-utils';

const ICONS_DIR = 'icons';

function main() {
  const iconNames = getAllIconNames(ICONS_DIR);

  // ─── Core package index ───
  const coreDir = join('packages', 'iconex', 'src');
  mkdirSync(join(coreDir, 'icons'), { recursive: true });

  const coreExports = iconNames.map((name) => {
    const pascal = toPascalCase(name);
    return `export { default as ${pascal} } from './icons/${name}';`;
  });

  const coreIndex = `// Auto-generated by scripts/generate-index.ts — do not edit manually

export type {
  IconNode,
  IconNodeChild,
  IconCategory,
  IconVariant,
  IconData,
  IconMeta,
  IconDefinition,
} from './types';

${coreExports.join('\n')}
`;

  writeFileSync(join(coreDir, 'index.ts'), coreIndex, 'utf8');
  console.log(`Generated core index.ts with ${iconNames.length} icon exports.`);

  // ─── React package index ───
  const reactDir = join('packages', 'iconex-react', 'src');
  mkdirSync(join(reactDir, 'icons'), { recursive: true });

  const reactExports = iconNames.map((name) => {
    const pascal = toPascalCase(name);
    return `export { default as ${pascal} } from './icons/${pascal}';`;
  });

  const reactIndex = `// Auto-generated by scripts/generate-index.ts — do not edit manually

// Hand-written exports
export { default as Icon } from './Icon';
export type { IconProps } from './Icon';
export { default as createIconexIcon } from './createIconexIcon';
export { IconexProvider, useIconexContext } from './IconexProvider';
export type { IconexContextValue, IconexProviderProps } from './IconexProvider';

// Re-export types from core
export type {
  IconCategory,
  IconVariant,
  IconNode,
  IconDefinition,
} from 'iconex';

// Icon component exports
${reactExports.join('\n')}

// Dynamic imports
export { default as dynamicIconImports } from './dynamicIconImports';
`;

  writeFileSync(join(reactDir, 'index.ts'), reactIndex, 'utf8');
  console.log(
    `Generated React index.ts with ${iconNames.length} icon exports.`,
  );

  // ─── Dynamic imports file ───
  const dynamicImports = iconNames.map((name) => {
    const pascal = toPascalCase(name);
    return `  '${name}': () => import('./icons/${pascal}'),`;
  });

  const dynamicFile = `// Auto-generated by scripts/generate-index.ts — do not edit manually

const dynamicIconImports: Record<string, () => Promise<{ default: React.ComponentType<any> }>> = {
${dynamicImports.join('\n')}
};

export default dynamicIconImports;
`;

  writeFileSync(join(reactDir, 'dynamicIconImports.ts'), dynamicFile, 'utf8');
  console.log('Generated dynamicIconImports.ts.');
}

main();
